services:
  nvidia-smi-exporter:
    image: ccmpbll/nvidia-smi-exporter:latest
    runtime: nvidia
    privileged: true
    ports:
      - "9202:9202/tcp"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=utility
    restart: unless-stopped
