services:
  nvidia-smi-exporter:
    image: ccmpbll/nvidia-smi-exporter:latest
    runtime: nvidia
    ports:
      - "9202:9202/tcp"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    restart: unless-stopped
